apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventrouter
  labels:
    app: eventrouter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventrouter
  template:
    metadata:
      labels:
        app: eventrouter
        tier: control-plane-addons
    spec:
      serviceAccount: eventrouter
      restartPolicy: Always
      containers:
        - name: kube-eventrouter
          image: steveww/eventrouter
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: /etc/eventrouter
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
      volumes:
        - name: config-volume
          configMap:
            name: eventrouter-cm
