apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: eventrouter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: eventrouter
  namespaceSelector:
    matchNames:
      - agent
  podMetricsEndpoints:
    - port: http
      path: /metrics
