name: Eventrouter

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      
      - name: Install Dependencies
        run: go mod download -x
      
      - name: Build Binary
        run: make build
      
      - name: Set repo and PR number
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER=${{ github.event.number }}
          echo "REPO_TAG=${PR_NUMBER}" >> $GITHUB_ENV
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          echo "REPO_NAME=${REPO_NAME}.dev" >> $GITHUB_ENV

      - name: Set repo and commit id
        if: github.ref == 'refs/heads/main'
        run: |
          SHORT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          echo "REPO_TAG=${SHORT_HASH}" >> $GITHUB_ENV
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          echo "REPO_NAME=${REPO_NAME}.dev" >> $GITHUB_ENV
      
      - name: Set repo and release tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "REPO_TAG=${TAG}" >> $GITHUB_ENV
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: '.'
          push: true
          tags: steveww/${{ env.REPO_NAME }}:${{ env.REPO_TAG }}
