name: Eventrouter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build and push image
    runs-on: ubuntu-latest
    outputs:
      version-tag: ${{ steps.version.outputs.version_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      
      - name: Install Dependencies
        run: go mod download -x
      
      - name: Build Binary
        run: make build
      
      - name: Set repo name
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          echo "REPO_NAME=${REPO_NAME}.dev" >> $GITHUB_ENV

      - name: Set PR number
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER=${{ github.event.number }}
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Build and push PR image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: '.'
          push: true
          tags: steveww/${{ env.REPO_NAME }}:PR-${{ env. PR_NUMBER }}
      
      - name: Set commit id
        if: github.ref == 'refs/heads/main'
        run: |
          SHORT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          echo "SHORT_HASH=${SHORT_HASH}" >> $GITHUB_ENV
      
      - name: Build and push staging image
        uses: docker/build-push-action@v4
        with:
          context: '.'
          push: true
          tags: steveww/${{ env.REPO_NAME }}:${{ env.SHORT_HASH }}
